version: '3'
services:
    nginx:
        image: nginx:latest
        # 端口映射
        ports:
            - "8081:80"
        # 依赖关系 先跑php
        depends_on:
            - "php74"
        # 数据卷
        volumes:
            # 映射主机./conf.d目录到容器/etc/nginx/conf.d目录
            - "$PWD/nginx/conf/locations.conf:/etc/nginx/locations.conf"
            - "$PWD/nginx/conf/nginx.conf:/etc/nginx/nginx.conf"
            - "$PWD/nginx/conf/conf.d:/etc/nginx/conf.d"
            - "$PWD/html:/usr/share/nginx/html"
            - ./html:/var/www
        networks:
          tp_network:
            aliases:
            - nginx
        # 容器名称
        container_name: "nginx"
    php74:
        build: ./php/php7.4        
        container_name: "php7.4"
        # image指定build Dockerfile生成镜像的名称
        ports:
            - "9000:9000"
        volumes:
            - "$PWD/html:/usr/share/nginx/html"
            - ./html:/var/www
            - "$PWD/php/php7.4/conf/conf.d/:/usr/local/etc/php/conf.d/"
            - "$PWD/php/php7.4/php.ini:/usr/local/etc/php/php.ini"
        networks:
          tp_network:
            aliases:
            - php7.4
            - php
  
networks:
  tp_network:
    external: true
    name: tp_network